server:
  port: 8002
spring:
  application:
    name: payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 1234

eureka:
  client:
    register-with-eureka: true #是否将自己注册进 eurekservice-urlaServer，默认为true
    fetch-registry: true #是否从 eurekaServer 抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url: #设置eureka sever交互的地址查询服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 30 #eureka客户端向服务端发送心跳的时间间隔（s）（默认是30）
#    lease-expiration-duration-in-seconds: 90 #eureka服务端在收到最后一次心跳后等待的时间上限（s）（默认是90），超时将剔除服务

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.blossom.springcloud.entity