server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true #是否将自己注册进 eurekservice-urlaServer，默认为true
    fetch-registry: true #是否从 eurekaServer 抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url: #设置eureka sever交互的地址查询服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka