server:
  port: 8004
spring:
  application:
    name: provider-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 1234
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.blossom.springcloud.entity